---
exclude:
    - ABOUT.md
    - README.md
    - Makefile
    - big_images
    - scripts
    - test
    - text
    - flash
    - audio
    - images
    - Gemfile
    - Gemfile.lock
    - pages
    - assets/images

collections:
    chapters:
        output: true
        permalink: /:path/

keep_files: [assets/images]
