---
exclude:
    - ABOUT.md
    - README.md
    - Makefile
    - big_images
    - scripts
    - test
    - text
    - flash
    - audio
    - images
    - Gemfile
    - Gemfile.lock

keep_files:
    - assets/images
    - assets/audio

collections:
    pages:
        output: true
        permalink: /pages/:title/

# defaults:
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: page
